[tools]
fzf = "0.67.0"
jq = "1.8.1"
neovim = "0.11.5"
python = "3.14.0t"
starship = "1.23.0"
bat = "0.26.0"
delta = "0.18.2"
go = "1.25.4"
node = "25.2.1"
zellij = "0.43.1"
helix = "25.07.1"
rclone = "1.72.0"
kind = "0.30.0"
kubectl = "1.34.2"
rust = "1.91.1"
uv = "0.9.11"
lazydocker = "0.24.1"
helm = "4.0.0"
restic = "0.18.1"
kubectx = "0.9.5"
